Traceback (most recent call last):
  File "/work/1/NBB/serihiro/src/chainer/chainermn/communicators/__init__.py", line 79, in create_communicator
    import mpi4py.MPI
ImportError: libimf.so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/work/NBB/serihiro/src/chainer/examples/chainermn/imagenet/evaluation_for_swopp/scripts/train_imagenet_extended.py", line 295, in <module>
    main()
  File "/work/NBB/serihiro/src/chainer/examples/chainermn/imagenet/evaluation_for_swopp/scripts/train_imagenet_extended.py", line 188, in main
    comm = chainermn.create_communicator(args.communicator)
  File "/work/1/NBB/serihiro/src/chainer/chainermn/communicators/__init__.py", line 81, in create_communicator
    raise ImportError(str(e) + ': '
ImportError: libimf.so: cannot open shared object file: No such file or directory: ChainerMN requires mpi4py for distributed training. Please read the Chainer official document and setup MPI and mpi4py.
